### ISSUE TITLE
Change main methods to unit tests

### ISSUE THREAD

**Issue by lexvanderstoep** [CvanderStoep/Genetic_Swarm#1]
Some of your main methods are used to test functionality of the code. It might be worthwhile to change these to unit tests.

For example, the `main` method in the `Individual` class tests whether fitness works. This should be placed in a unit test

**Comment by CvanderStoep** [comment]
Deed jij een voorzet?

**Comment by CvanderStoep** [comment]
de test doet het; dankjewel.
hoe run ik alle tests in de folder test?
ik kan wel mazetest runnen, maar stel je voor dat ik meer Unit tests heb
als ik op de folder test ga staan, zie ik wel het commando run test in test; maar dat doet niet veel 
de class Mazetest geeft een melding dat hij een package mist?

**Comment by lexvanderstoep** [comment]
Right-click op je module, en dan komt er een actie tevoorschijn genaamd “Run All Tests”

**Comment by lexvanderstoep** [comment]
Als je naar de MazeTest class gaat, naar de regel met de melding dat je een pakket mist, dan komt er zo’n lampje tevoorschijn. Als je daar op klikt kan je op import klikken volgens mij

**Comment by CvanderStoep** [comment]
ik kreeg 2 meldingen:
bij junit.jupiter de melding dat ik iets moest doen; gedaan, gelukt
bij class Mazetest een melding "missing package statement", volgens mij is dat omdat het in de folder test staat. Als je nu boven de class zet: package test, dan worden vervolgens als onderliggen classes weer niet herkent.

**Comment by lexvanderstoep** [comment]
<img width="316" alt="image" src="https://user-images.githubusercontent.com/9699982/57692190-12626900-763e-11e9-8485-d2c58bb515af.png">

Zo ziet mijn project er uit. De "test" folder is gemarkeerd als test folder (right-click op de folder > Mark As > Test root)

**Comment by CvanderStoep** [comment]
Die optie heb ik niet.
Alleen mark directory as excluded.

Carlo

**Comment by lexvanderstoep** [comment]
Genetic_Swarm > right_click > Module Settings >:

<img width="1018" alt="image" src="https://user-images.githubusercontent.com/9699982/57693048-2c04b000-7640-11e9-9941-dc8cf712fd37.png">

Klik dan op de 'test' folder, and selecteer de test mark as

**Comment by CvanderStoep** [comment]
Hoera!

Carlo
