### ISSUE TITLE
mazesize as input in individual

### ISSUE THREAD

**Issue by CvanderStoep** [CvanderStoep/Genetic_Swarm#2]
Lex,
Ik weet niet hoe ik een verzoek moet maken, dus dan maar een issue:
In de class individual zit een start & target locatie, die wil ik afhankelijk maken van de mazeSize.
In VB gebruikte ik hiervoor een globale var :-( 
Wat is hier de beste constructie?

**Comment by lexvanderstoep** [comment]
Je kan de `mazeSize` meegeven aan de constructor van `Individual`. Vervolgens kan je daar dan in de constructor mee doen wat je wilt.

**Comment by CvanderStoep** [comment]
is gedaan en gepusht.
ik ben alleen nog niet tevreden met de crossover method in de individual class
Er wordt hier intern weer een nieuwe constructor aangeroepen met interne data van de oude??
Het gaat wel goed, maar het voelt niet goed...

**Comment by lexvanderstoep** [comment]
Ziet er prima uit imo
