### ISSUE TITLE
Input form - run simulation.main

### ISSUE THREAD

**Issue by CvanderStoep** [CvanderStoep/Genetic_Swarm#4]
Lex,
Ik heb een input form gemaakt en ik probeer vanuit de run button de "routine" simulation.main aan te roepen. Volgens mij maak ik hier een denkfout?

Ik de variabelen al in de constructor gezet, maar toch krijg ik een leeg scherm zonder actie te zien?

Ideeen?

**Comment by CvanderStoep** [comment]
aanvulling: het programma runt wel, maar laat pas op het allerlaatst het eindscherm zien.

**Comment by lexvanderstoep** [comment]
Ik denk dat het fout gaat omdat er twee forms worden getekend vanuit een thread. 

Als je het input programma opstart, dan wordt er een thread gestart die bij dat input venster hoort. Deze regelt dingen als het tekenen van het venster, luisteren naar events, etc. Als je vanuit het input venster, een ander venster gaat aanmaken (`StdDraw` aanroepen maakt een nieuw venster aan), dan gaan dingen raar doen.

Wat je kan proberen is om een nieuwe thread aan te maken en vanuit daar de `Simulation.main` aanroepen. Zie [hier](https://stackoverflow.com/questions/3489543/how-to-call-a-method-with-a-separate-thread-in-java). Je zoekt denk iets in de vorm van het volgende:

`new Thread(() -> {`
`//       code goes here.`
`}).start();`

**Comment by CvanderStoep** [comment]
yep, dit lost het issue op. Met letterlijk jouw 2 regels code om het commando simulation.main()
(ik heb het nog niet gepusht, krijg een foutmelding in GitHub)
