### ISSUE TITLE
Multiple simulations

### ISSUE THREAD

**Issue by lexvanderstoep** [CvanderStoep/Genetic_Swarm#5]
Wanneer je een simulation start vanuit de input form, kan je daarna er nog een starten. Als je dat dan breekt de hel los and worden er meerdere dingen over elkaar geplot. Je kan het proberen te disabelen (dat je er maar één kan starten) of je kan proberen meerdere plots te hebben.

**Comment by CvanderStoep** [comment]
ik heb gekozen voor de makkelijke route, btnRun.enable(false) nadat je 'm een keer hebt ingedrukt.
